### PR TITLE
#130-signUp page

### LINKED ISSUE #130: [STYLE CHANGE] Tailler-Customer signUp page
**Description:**
I would like to change ui of signUp page for customer and tailer

**Reason for Change:**
They are not that great looking and not that responsive

**Current Styling:**

scrnli_25_05_2023_20-55-48

### PR DESCRIPTION
**Pull request by Soulpurr**
# Description
I have refactor the signUp page. As per your instruction i have kept the theme same.

Fixes #130 

## Type of change
Styling

ScreenShots-
[scrnli_28_05_2023_17-12-45.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/1ebfc9a4-e2fe-4441-9a54-b710a7dca065)

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Soulpurr!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Soulpurr** [comment]
@Naresh-chandanbatve can you please approve this pr.

**Review by Naresh-chandanbatve — CHANGES_REQUESTED** [review]
Input fields are left aligned 
align them at centre
Decrease the button size of register and sign up with google buttons and align both input fields and buttons properly in centre

**Comment by Soulpurr** [comment]
HII @Naresh-chandanbatve  i have aligned input tags to centre and decrease the size of buttons

**Comment by Soulpurr** [comment]
screenshots
scrnli_28_05_2023_20-32-40

**Review by Naresh-chandanbatve — APPROVED** [review]

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
Check the mobile view it's not responsive properly icons are overlapping with the text sections

**Review by Naresh-chandanbatve — CHANGES_REQUESTED** [review]
You have miss aligned placeholder in mobile
And also you have hidden the toggle password visibility button 
Check for it

**Comment by Naresh-chandanbatve** [comment]
@Soulpurr 
As the issue assigned to you is already resolved
And merging this pr will not make any successful change 
We are rejecting this pr

**Pull request closed without merging**
