### PR TITLE
added footer UI

### LINKED ISSUE #211: [FEATURE REQUEST] adding proper footer section on the website
## Description

there is no footer section available on the website

**Describe the solution you'd like**
I designed this footer section for this site
footer design

I would like to add this design to your website's footer section

## Additional Information

**Context**
Additionally, I will add some hover effects in the links. and the logo will redirect to the main page

**Additional Notes** (optional)
if you provide me with more social links, I will add that too.

kindly assign this task to me under GSSOC'23 contributor

### PR DESCRIPTION
**Pull request by Iamdivyak**
# Description

- Added footer section
- added some hover effects in the links. and the logo redirects to the main page

Fixes #211

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots
image

## Before
there wan no footer
## After
added footer

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Iamdivyak!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @Iamdivyak ,
I went through your changes, and you have made a pretty good footer, but there are some changes to it
1. You have directly made your changes in client/StichHub/src/components/MainLandingPage/Footer.jsx ,
    Firstly, **retrieve all the code of Footer.jsx** in that file, as it was before  
    **Make a new file** named **FooterHomePage.jsx** and add you new code there.
2. Add some dark **background color** to your footer.
3. Your footer is not responsive, **make it responsive**.
image

4. **Add link in login and register**, use react-router-dom `<Link to="/auth">` in both, as of now
image

5. Fix **Contact Us spelling**.
image

Kindly make these changes and then pin me

**Comment by Iamdivyak** [comment]
hey, @Siddhant-Patil0203 sorry for the delay. 
I've made the changes that you asked for.
Could you review it again?

I'm new in git, so I'm sure I've done everything correctly.🥲
please guide me if I've done something wrong because the checks didn't pass.

**Review by Naresh-chandanbatve — APPROVED** [review]

**Comment by Naresh-chandanbatve** [comment]
Thank you @Iamdivyak 
for your contribution...

**Pull request merged**
