### PR TITLE
Improve Lighthouse Accessibility and SEO

### LINKED ISSUE #133: [BUG] Improve Lighthouse Accessibility and SEO
## Description

**Describe the bug:**
Images used in the website do not have the ALT attribute and multiple elements have the same ID attribute.

**Expected behaviour:**
The Lighthouse results should have 100 in Accessibility and SEO

**Actual behaviour:**
The Lighthouse results are below 100.

## Reproduction Steps

**Steps to reproduce the behaviour:**

1. Go to https://stichhub-chi.vercel.app/
2. Open Chrome Dev Tools 
3. Go to the Lighthouse tab and click Analyze Page Load

## Screenshots

Screenshot 2023-05-26 at 1 37 47 PM

Screenshot 2023-05-26 at 1 43 56 PM

Screenshot 2023-05-26 at 1 44 17 PM

## Additional Information

**Device (please complete the following information):**
- OS: macOS
- Browser Chrome
- Version latest

**Additional context:**

- [x] There is no similar existing open issue
- [x] This is a part of GSSOC'23

### PR DESCRIPTION
**Pull request by rahulaarora**
# Description

Fixes duplicate id, aria-label in links and extra left margin in demo buttons on the homepage

Fixes #133 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] LightHouse Test

- Go to the homepage
- Open Chrome Dev Tools
- Go to the Lighthouse tab and click Analyze Page Load

**Test Configuration**:
* Browser version: Chrome latest
* Software version: macOS latest

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## After
Screenshot 2023-05-31 at 12 45 56 AM

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @rahulaarora!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @rahulaarora 

I just check the lighthouse performance for your pull request deployment Preview and its shows this
image

Can you try to improve SEO more 
Also, check about crawling for this site as it says this :
image

**Comment by rahulaarora** [comment]
> Hey @rahulaarora
> 
> I just check the lighthouse performance for your pull request deployment Preview and its shows this image
> 
> Can you try to improve SEO more Also, check about crawling for this site as it says this : image

sure I will look into this and improve the SEO

**Comment by parthpathakpp1** [comment]
> sure I will look into this and improve the SEO

@rahulaarora I need some help . Can you please share your Discord id ?

**Comment by rahulaarora** [comment]
> @rahulaarora I need some help . Can you please share your Discord id ?

rahularora#2885

**Comment by rahulaarora** [comment]
Hey @Siddhant-Patil0203, I checked on the localhost again with the updated branch, and the result looks good.
Here's the attached ss:
Screenshot 2023-06-04 at 1 49 08 PM

The crawling issue in the SEO section is because of the deployment preview link on which you measured the LightHouse metrics as vercel prevents the preview links from indexing in the search engine.

**Comment by rahulaarora** [comment]
@Siddhant-Patil0203 please review

**Review by UBA-GCOEN — APPROVED** [review]

**Pull request merged**
