### PR TITLE
Added scroll to top option in some long pages[GSSoC'23]

### PR DESCRIPTION
**Pull request by Deepanshu0703**
Added scroll to top option in some long pages having a react-icon in a circle and doesn't appear when you are already at top

### CODE REVIEW

**Comment by Naresh-chandanbatve** [comment]
Add your all changes done in this pr
Add on which pages you have added this button.

**Review by Naresh-chandanbatve — CHANGES_REQUESTED** [review]
In Mobile view the scroll up button is overlapping  content
It should be placed on right bottom side

**Comment by Naresh-chandanbatve** [comment]
Have you done changes in mobile view only or in desktop also

**Comment by Deepanshu0703** [comment]
I have added this functionality to main page  homeOnlineVisit and clothes category in both mobile and desktop view . Resolved this mobile view overlapping issue.

**Review by Naresh-chandanbatve — APPROVED** [review]

**Comment by Deepanshu0703** [comment]
please assign it a level

**Pull request merged**
