### PR TITLE
[ISSUE #16] Improvement in the demo section

### PR DESCRIPTION
**Pull request by whodivyanshu**
I have added scrollbar in the demo section of that page 
also I have added some height in that section 

before : 
image

after: 
image

I have added the height so that the scroll bar works fine

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @whodivyanshu!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by whodivyanshu** [comment]
@Naresh-chandanbatve kindly review this and tell me if there is a need of extra styling

**Comment by Naresh-chandanbatve** [comment]
Jave you created issue for this

**Comment by whodivyanshu** [comment]
Yes

**Comment by UBA-GCOEN** [comment]
Hello @whodivyanshu!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by whodivyanshu** [comment]
I had my exams so I thought If I dont do a pr asap then this issue will be assigned to someone else

**Comment by whodivyanshu** [comment]
but the end gold of the issue was this only that the bottom buttons were not quite visible

**Comment by UBA-GCOEN** [comment]
Hello @Naresh-chandanbatve!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
