### PR TITLE
Overflow issue in registration section is resolved

### PR DESCRIPTION
**Pull request by HimanshuNarware**
# Description
The overflow issue in Tailor Register is resolved, and also fix some styling issues in the registration page

Fixes # (issue)
#26

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

By using localhost in my device and also on a small device like a mobile phone

- [x] Test A
- [x] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
overflow

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @HimanshuNarware!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @HimanshuNarware!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @HimanshuNarware!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Naresh-chandanbatve** [comment]
@Siddhant-Patil0203 check this in laptop for different sizes.

**Comment by HimanshuNarware** [comment]
> @Siddhant-Patil0203 check this in laptop for different sizes.

already checkded

**Comment by UBA-GCOEN** [comment]
> @Siddhant-Patil0203 check this in laptop for different sizes.

image

@HimanshuNarware 
It is still not responsive for iphone SE, rest it works with most of the devices.
Pls do the needful for iphone SE dimensions

**Comment by HimanshuNarware** [comment]
> > @Siddhant-Patil0203 check this in laptop for different sizes.
> 
> image
> 
> @HimanshuNarware It is still not responsive for iphone SE, rest it works with most of the devices. Pls do the needful for iphone SE dimensions

ok sir

**Pull request closed without merging**
