### PR TITLE
Issue 139:improving card items

### LINKED ISSUE #139: [STYLE CHANGE] Improving card items
**Description:**
These card items are not that great so i want to work on their styling like adding a hovering effect that eases them in or out.

**Reason for Change:**
These cards are important from user point of view.

scrnli_26_05_2023_16-51-16

### PR DESCRIPTION
**Pull request by Soulpurr**
# Description
I have refactored the card items taking the theme same.
I have added a hover effect on them.
Plus if a user doesn't provide his image it will now display a dummy image in order to enhance experience.
Moreover the space you see inside the card is due to the fact that some people doesn't provide any tags thats not a bug.
Moreover if you want me to add a dummy tag i will implement it but i dont think dummy tag will make any sense.
Fixes #139 

ScreenShots-
[scrnli_29_05_2023_08-57-48.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/f985144e-1a66-4c5c-9242-7e72e661c6dd)

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Soulpurr!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by BaibhavTiwari** [comment]
> # Description
> I have refactored the card items taking the theme same. I have added a hover effect on them. Plus if a user doesn't provide his image it will now display a dummy image in order to enhance experience. Moreover the space you see inside the card is due to the fact that some people doesn't provide any tags thats not a bug. Moreover if you want me to add a dummy tag i will implement it but i dont think dummy tag will make any sense. Fixes #139
> 
> ScreenShots- [scrnli_29_05_2023_08-57-48.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/f985144e-1a66-4c5c-9242-7e72e661c6dd)

@Soulpurr I can clearly see that you have done a great job in fixing the alignment of the Cards as well as by adding the hover effect. 
>
hh

As you can clearly see from the Screenshot the words `Result` and `welcome` are not Visible properly and the same goes for the logo . I was going to create an issue for it but as, I seen your PR it would like you to make the changes if possible.

**Comment by Soulpurr** [comment]
@BaibhavTiwari actually that was not the part of my issue.My issue was to improve card items you can create a issue to fix the problem you stated above or I will do it by creating a new issue after this pr is merged

**Comment by BaibhavTiwari** [comment]
> @BaibhavTiwari actually that was not the part of my issue.My issue was to improve card items you can create a issue to fix the problem you stated above or I will do it by creating a new issue after this pr is merged

I know this was not the part of your issue. I just suggested you to do this as you are working on the Home page you can commit the changes in this PR too, if you like

**Comment by Soulpurr** [comment]
@BaibhavTiwari ahh will do it

**Comment by Siddhant-Patil0203** [comment]
Hey @Soulpurr 
Can you keep the style of tags as it was before i.e. background color and font color
Also, remove the X sign from the tags

**Comment by Soulpurr** [comment]
@Siddhant-Patil0203 i have made the requested changes can verify are they visible.

**Review by Siddhant-Patil0203 — APPROVED** [review]
@Soulpurr Great Work!!

**Comment by Soulpurr** [comment]
Hii @Naresh-chandanbatve  @Siddhant-Patil0203 @its-vikash  since this pr was merged pls add level and gssoc23 label  to this as due to this the leaderboard doesn't count this pr.

**Pull request merged**
