### PR TITLE
New Card added

### PR DESCRIPTION
**Pull request by Hemant2335**
# Description

I have changed the cards in the dashboard and I haven't used any dependencies at all also i have only made the changes in the required file only

But I have added a new need in the project of also adding the image of working place of the tailor .

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

And this isn't the final change , Please provide any feedback on this

here are the ss
Screenshot (85)
Screenshot (86)

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Hemant2335!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
@Hemant2335 which issue does this fixes

**Comment by Hemant2335** [comment]
Issue #44

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
Hey @Hemant2335 ,
Your design is not responsive
image

Kindly make it responsive.

**Comment by Hemant2335** [comment]
I have made some changes now it is quite responsive please check

ss
Screenshot (92)
Screenshot (93)

**Comment by Hemant2335** [comment]
A minor change also

ss
Screenshot (94)

**Comment by Siddhant-Patil0203** [comment]
Hey @Hemant2335 
Can you pls align the **Book now** and **more details** buttons properly?

Your Changes shows
image

Make it like this
image
Buttons are covering the whole cards and are aligned in a column

**Comment by Hemant2335** [comment]
check it now 

ss
Screenshot (95)
Screenshot (96)

**Comment by Siddhant-Patil0203** [comment]
@Hemant2335 Recently, the hover effect was added to the cards, also the dummy icons, and some minor UI/UX changes to the card you are working on, kindly first pull the changes, resolve the conflicts if any, and don't override the new changes.
Thank you 🙂

**Comment by Naresh-chandanbatve** [comment]
@Hemant2335 
Done ?

**Comment by Hemant2335** [comment]
> @Hemant2335 Done ?

Yes it is done now 

ss
Screenshot (98)
Screenshot (97)

**Comment by Naresh-chandanbatve** [comment]
@Siddhant-Patil0203

**Comment by Siddhant-Patil0203** [comment]
Hey @Hemant2335 

> @Hemant2335 Recently, the hover effect was added to the cards, also the dummy icons, and some minor UI/UX changes to the card you are working on, kindly first pull the changes, resolve the conflicts if any, and don't override the new changes. Thank you 🙂

You haven't accepted this changes, pls accept this changes of this PR #196

**Comment by Hemant2335** [comment]
Could you please tell how am I able to do that
-> When I am not having any conflicts 
-> And also last time I tried that but that completely reverted my all changes
if you have any solution please suggest

**Comment by Siddhant-Patil0203** [comment]
> Could you please tell how am I able to do that -> When I am not having any conflicts -> And also last time I tried that but that completely reverted my all changes if you have any solution please suggest

Checkout to a commit before, when there was a conflict with your branch.
then make a pull request,
when you make a pull request there will be conflicts,
Check you GitHub extension in vs code, it will ask you to resolve merge conflicts

 
image

There are three options for resolving conflicts:
- Accept current change.
- Accept incoming change.
- Accept both changes.
These options are self-explanatory. Clicking the options will apply the action they describe. Conflicts can be inline. For those, you can just edit the file in VS Code.️️️

You can also refer to this blog : https://learn.microsoft.com/en-us/visualstudio/version-control/git-resolve-conflicts?view=vs-2022

**Comment by Hemant2335** [comment]
Thanks for your I'll be resolving the issue soon

**Comment by Hemant2335** [comment]
I have added the effects from that merge please check 

here ss
Screenshot (104)
Screenshot (105)

**Comment by Naresh-chandanbatve** [comment]
@Siddhant-Patil0203

**Comment by Hemant2335** [comment]
I have made above requested changes please check and also this and also this pr is under Gssoc.

Thank you

here are ss

Screenshot (144)
Screenshot (145)
Screenshot (146)

**Comment by Siddhant-Patil0203** [comment]
@Hemant2335 So sorry, there was a little typing error for me.

I mean to say this 
When we hover over any card, it blurs the content, but it should not, it should be clear 
image

Can you please look through this

**Comment by Naresh-chandanbatve** [comment]
Have you used blur effect on hover?

You can use backdrop filter it will blur the background only on hover not content.
Have a search

**Comment by Hemant2335** [comment]
No I haven't used any effect on hover other than scaling  but Let me try to do it again thanks

**Comment by Hemant2335** [comment]
Please check this effect now there is no blurriness.

ss
Screenshot (149)

**Review by Siddhant-Patil0203 — APPROVED** [review]
@Hemant2335 Great Job ✨👀🚀

**Comment by Hemant2335** [comment]
I have made a new PR please check .

**Comment by Hemant2335** [comment]
> @Hemant2335 Great Job ✨👀🚀

Thank you ☺

**Pull request closed without merging**
