### PR TITLE
fix: fixed Log out in Tailor Profile Verification

### PR DESCRIPTION
**Pull request by ar-ag**
The pr resolves issue https://github.com/UBA-GCOEN/StichHub/issues/28.

The logout button in the TailorProfileVerification now redirects to /auth/tailor, and clears the localStorage off the details of the tailor, so that tailor is logged out from the website.

image

The TailorProfileVerification webpage, storing the details of logged in tailor in the localStorage.

image
After clicking 'Log Out', redirects back to /auth/tailor and clears the localStorage off the details of the tailor.

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @ar-ag!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @Naresh-chandanbatve!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Naresh-chandanbatve** [comment]
Why there ia change in client/ .env

**Comment by UBA-GCOEN** [comment]
Hello @Naresh-chandanbatve!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @ar-ag!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by ar-ag** [comment]
@Naresh-chandanbatve sorry that was a mistake, resolved it now.

could you please review it now.

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
