### PR TITLE
Improved timeline style for mobile screen size.

### LINKED ISSUE #132: [STYLE CHANGE] Modify "How it works " Timeline.
**Description:**

- Improve styling of the timeline in "How it Works for Customers" and "How it Works for Tailors."
- Reduce the margins for mobile/tablet displays.
- Make a vertical timeline for "How it Works for Customers" and "How it Works for Tailors." sections for Mobile displays for better UI.

[SCREENSHOTS]
Screenshot 2023-05-26 115917

Screenshot 2023-05-26 120759

### PR DESCRIPTION
**Pull request by harshit-002**
Fixes #132 

# Description
Made the "How it works for customers and tailors " timeline vertical for mobile view.
Changed timeline color to match the webpage color theme.

## Type of change
Style change

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
image

image

## After
image
image

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @harshit-002!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @harshit-002 
Your code is not responsive, and also vertical timeline is not looking good in mobile view.

So do you have any good idea to showcase how it works in vertical?

**Comment by harshit-002** [comment]
tailwind css doesn't have any class for extra small screen size, I can't make it responsive for less than w:640px just by changing the classes. I shall close the issue.

**Comment by Siddhant-Patil0203** [comment]
> tailwind css doesn't have any class for extra small screen size, I can't make it responsive for less than w:640px just by changing the classes. I shall close the issue.

@harshit-002 Actually tailwindcss is mobile-first, its all classes are by default for the mobile screen

**Pull request closed without merging**
