### PR TITLE
Form Validations, Loading state and FormSubmit Ajax implemented in Contact Us Form

### LINKED ISSUE #118: Contact form not working on the home page
**Describe the bug**
The contact form at the bottom of the home page is not functional.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://stichhub-chi.vercel.app/
2. Scroll down to the bottom contact form
4. Enter the details and submit and nothing happens

**Expected behaviour**
A successfully submitted or error message should be displayed to the user.

**Screenshots**
Screenshot 2023-05-24 at 3 23 09 PM

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Realme 6
 - OS: Android 11
 - Browser Chrome
 - Version latest

**Additional context**
The submit handler in the code of contact form is not yet implemented.

- [x] There is no similar existing open issue
- [x] This is a part of GSSoC'23

### PR DESCRIPTION
**Pull request by rahulaarora**
**NOTE: replace the email in `ContactUs.jsx` with the random string generated by formsubmit.co sent to your mail**

# Description

- Form validations implemented in the contact us form on the home page to prevent empty or wrong submissions.
- Form loading state implemented using useState hook for loading functionality.
- FormSubmit POST request implemented to send form data to email without backend and removing previous `action` attribute to implement loading functionality.

Fixes #118 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [x] Multiple types of input

Different types of inputs are checked on the form for proper validation.

- [x] Personal host email

The form is tested using the personal email account to verify the data is successfully sent to the email.

**Test Configuration**:
* Browser version: Chrome latest
* OS version: macOS latest

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots
Screenshot 2023-06-04 at 3 26 03 PM

Screenshot 2023-06-04 at 3 30 33 PM

### CODE REVIEW

**Comment by rahulaarora** [comment]
@Naresh-chandanbatve please review

**Comment by UBA-GCOEN** [comment]
Hello @rahulaarora!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by rahulaarora** [comment]
@Naresh-chandanbatve please review

**Review by Siddhant-Patil0203 — APPROVED** [review]
@rahulaarora  Great Work 🚀

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
Hey @rahulaarora 
instead of alerting, we can update the button itself 
let's do something like this 
sendbutton

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
@rahulaarora  Looks cool, just a few things
1. email validation does not accept dot, it should accept that email, for eg. xyx.123@gmail.com is shown as invalid, but it should be a valid email xyz[dot]123@gamil.com should be accepted.

2. After sending the any message, it get stucks on send button like this 
image
Use `setTimeout()` and keep a delay of 3s (3000), and then change the button again to submit.
3. Try to keep the button animation more simplistic and smooth.

👨‍💻😄

**Comment by Siddhant-Patil0203** [comment]
Hey, @rahulaarora pls. resolve the conflicts

**Comment by Siddhant-Patil0203** [comment]
@rahulaarora

**Comment by rahulaarora** [comment]
> @rahulaarora

sure

**Comment by Naresh-chandanbatve** [comment]
resolved conflict 
LGTM

**Review by Naresh-chandanbatve — APPROVED** [review]

**Comment by Naresh-chandanbatve** [comment]
Hey @rahulaarora  
Build is failing due to some issues can you check
Also resolve conflicts in contactus.jsx

Screenshot_2023_0713_190326

**Pull request closed without merging**
