### PR TITLE
Same email bug fix

### LINKED ISSUE #451: [Bug]: Tailor and customer with same email
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Description

I can create tailor and customer account with the same email which is generally not a common practice on websites that have two types of user.  For example, on the freelancing site **Fiverr** we cannot create a buyer and a seller account with the same Email. Similarly, it should not happen on our site too.

## Solution
We can prevent this behavior by implementing logic in the backend. I would like to solve this issue. 
If you find this worth implementing then please assign me this under the gssoc23 label.

### Add ScreenShots

**User Registration**

https://github.com/UBA-GCOEN/StichHub/assets/86224794/629ec50f-ca2c-4bfb-9866-db5e4962ffb4

**Tailor registration**

https://github.com/UBA-GCOEN/StichHub/assets/86224794/c38c2c49-b290-40a8-964d-1512bf18dff5

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Added logic to prevent creating different types of accounts with the same email.

Fixes #451 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Sample Output

https://github.com/UBA-GCOEN/StichHub/assets/86224794/10e239a7-8e40-453e-8fb9-5bbf819c11f5

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @AlfiyaSiddique!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by AlfiyaSiddique** [comment]
Hello @Siddhant-Patil0203 
Please review my PRs

**Comment by Siddhant-Patil0203** [comment]
> Hello @Siddhant-Patil0203 Please review my PRs

Yup we do it as soon as possible

**Review by Siddhant-Patil0203 — COMMENTED** [review]
@AlfiyaSiddique Looks Good

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Pull request merged**
