### PR TITLE
footer Updated

### LINKED ISSUE #402: [Style Update] : Footer UI Updated & Adding Youtube Video
The Current Style of the Footer is : 
image
This UI should be Updated 

The Footer should contain : 
1. This Youtube video: https://www.youtube.com/watch?v=dE3RYo23eSY
2. Social Media Handle : Email | Github | Youtube | Instagram | Twitter | Discord
    - Email: stichhub.office@gmail.com
    - Github : https://github.com/UBA-GCOEN/StichHub
    - Youtube: https://www.youtube.com/@StichHub_YT
    - Instagram: https://www.instagram.com/stichhub_/
    - Twitter : https://twitter.com/StichHub_
    - Discord : keep it blank as of now
3. Privacy Policy: use a standard template for now
4. Terms and Condition: use a standard template for now
5. License: https://github.com/UBA-GCOEN/StichHub/blob/main/LICENSE

You free to design and style the footer on your own, 
Checkout [Dribbble](https://dribbble.com/search/shots/popular/web-design?q=footer) Site for design inspiration

### Those who are interested in working this can tag me.

### PR DESCRIPTION
**Pull request by PatilHarshh**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #402 

## Type of change
footer Updation

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## After

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @PatilHarshh!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by PatilHarshh** [comment]
Screenshot (136)

**Comment by Naresh-chandanbatve** [comment]
@PatilHarshh
in the footer you have added the video link n the social youtube icon instead the youtube icon should redirect to youtube channel of stichhub not the video link the link of youtube channel is provided in the issue.

also add the video in other place which is provided in the issue 
like add the video at left side of footer text and the video should be played automatically 


also this pr is also breaking preloader and making preloader design to change make the preloader s it was earlier.

**Comment by Naresh-chandanbatve** [comment]
hope it makes you clear
ping me if you did not understand anything?

**Review by Naresh-chandanbatve — CHANGES_REQUESTED** [review]
make the changes

**Comment by Naresh-chandanbatve** [comment]
also can you remove the css file and do the same effect using tailwind css as our code structure includes tailwind css

**Comment by PatilHarshh** [comment]
> @PatilHarshh in the footer you have added the video link n the social youtube icon instead the youtube icon should redirect to youtube channel of stichhub not the video link the link of youtube channel is provided in the issue.
> 
> also add the video in other place which is provided in the issue like add the video at left side of footer text and the video should be played automatically
> 
> also this pr is also breaking preloader and making preloader design to change make the preloader s it was earlier.

did'nt understand video left ! means ? @Naresh-chandanbatve

**Comment by PatilHarshh** [comment]
> also can you remove the css file and do the same effect using tailwind css as our code structure includes tailwind css

i will try to do if it is possible for me ! @Naresh-chandanbatve

**Comment by Naresh-chandanbatve** [comment]
@PatilHarshh 
any updates?

**Comment by PatilHarshh** [comment]
yes working @Naresh-chandanbatve

**Comment by PatilHarshh** [comment]
> > @PatilHarshh in the footer you have added the video link n the social youtube icon instead the youtube icon should redirect to youtube channel of stichhub not the video link the link of youtube channel is provided in the issue.
> > also add the video in other place which is provided in the issue like add the video at left side of footer text and the video should be played automatically
> > also this pr is also breaking preloader and making preloader design to change make the preloader s it was earlier.
> 
> did'nt understand video left ! means ? @Naresh-chandanbatve

.

**Comment by PatilHarshh** [comment]
@Naresh-chandanbatve no brother it is not working on tailwind css as i tried it is not showing waves  !!

**Comment by PatilHarshh** [comment]
please reply me ASAP!!

**Comment by PatilHarshh** [comment]
@Naresh-chandanbatve reply expected fast  please !!

**Comment by PatilHarshh** [comment]
@Naresh-chandanbatve please merge it now

**Pull request closed without merging**
