### PR TITLE
updated readme

### LINKED ISSUE #164: [Documentation Update] Update Maintainers Section in README
## Issue ‼️ :
Currently the [Maintainer](https://github.com/UBA-GCOEN/StichHub#maintainers-) Section is like this :
image

## How it should be ✅: 
1) Update the Title from **Maintainers** to **Project Admin**
2) There should be a proper Profile Photo and name of the project admins
3) After Clicking it should Redirect to the Project admin's Social Profile.

## Resources 📃:

1) Project Admins Social Profile links :
  - Siddhant Patil (Project Lead) 
     - Github: https://github.com/Siddhant-Patil0203 
     - LinkedIn: https://www.linkedin.com/in/sidd0203
     - Instagram: https://www.instagram.com/sidd.0203/
     - Twitter: https://twitter.com/Sidd0203
  - Naresh Chandanbatve 
     - Github: https://github.com/Naresh-chandanbatve
     - LinkedIn: https://www.linkedin.com/in/naresh-chandanbatve
     - Instagram: https://www.instagram.com/naresh_chandanbatve/
     - Twitter: https://twitter.com/NareshChandanb1
  - Harshal Lade 
     - Github: https://github.com/LadeHarshal
     - LinkedIn: https://www.linkedin.com/in/harshal-lade-08749a214/
     - Instagram: https://www.instagram.com/harshallade2/
     - Twitter: https://twitter.com/Sidd0203
  - Vishal Kesharwani 
     - Github: https://github.com/vishal10kesharwani
     - LinkedIn: https://www.linkedin.com/in/vishal-kesharwani-1004vs/
     - Instagram: https://www.instagram.com/dev.vishalvsk/
     - Twitter: https://twitter.com/Vishal46255005
  - Saurabh Yadav 
     - Githbu: https://github.com/Saurabb-coder
     - LinkedIn: https://www.linkedin.com/in/saurabh-yadav-469323208/
     - Instagram: https://www.instagram.com/saurabh739/
     - Twitter: https://twitter.com/Sidd0203

_**Note 📝:  Search for the best Readme Admin Template from other repositories or the internet.**_

### PR DESCRIPTION
**Pull request by Tushar98644**
fixes #164 

@UBA-GCOEN pls review

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Tushar98644!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by Naresh-chandanbatve — CHANGES_REQUESTED** [review]
Some admin photos are large and some are small
Resize it to the size of readme in this repository
 https://github.com/SauravMukherjee44/CodeIN-Community-Website

And add small icons of social like github, LinkedIn, twitter below the image and add link of social in the icon

**Comment by Naresh-chandanbatve** [comment]
@Tushar98644

**Comment by Tushar98644** [comment]
> @Tushar98644

updated

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
