### PR TITLE
Card UI Improvement

### PR DESCRIPTION
**Pull request by SubhamB2003**
# Description
Issue Solved: #326 

@Siddhant-Patil0203  can please review it

Before
image

image

After
image

image

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

## After

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @SubhamB2003!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by its-vikash** [comment]
@SubhamB2003  Please use old font style that was used earlier and on a  smartphone view, try to align price and "Book Appointment" in a single line. It will look much better and font size of "Address details" should be lower than the font size of "About the Tailor".
Also add a description box that shows that shows name of tailor and contact details .
You can put address details inside contact details

**Comment by SubhamB2003** [comment]
> @SubhamB2003 Please use old font style that was used earlier and on a smartphone view, try to align price and "Book Appointment" in a single line. It will look much better and font size of "Address details" should be lower than the font size of "About the Tailor". Also add a description box that shows that shows name of tailor and contact details . You can put address details inside contact details

Hey, where is the tailor name and contact details?

**Comment by its-vikash** [comment]
> > @SubhamB2003 Please use old font style that was used earlier and on a smartphone view, try to align price and "Book Appointment" in a single line. It will look much better and font size of "Address details" should be lower than the font size of "About the Tailor". Also add a description box that shows that shows name of tailor and contact details . You can put address details inside contact details
> 
> Hey, where is the tailor name and contact details? can you please help me?
> 
> Is it ok?
> 
> image

@SubhamB2003 please send the screenshot of mobile view

**Comment by SubhamB2003** [comment]
> > > @SubhamB2003 Please use old font style that was used earlier and on a smartphone view, try to align price and "Book Appointment" in a single line. It will look much better and font size of "Address details" should be lower than the font size of "About the Tailor". Also add a description box that shows that shows name of tailor and contact details . You can put address details inside contact details
> > 
> > 
> > Hey, where is the tailor name and contact details? can you please help me?
> > Is it ok?
> > image
> 
> @SubhamB2003 please send the screenshot of mobile view

Yeah 
Also, I remove the unused bottom space

image

**Comment by its-vikash** [comment]
@SubhamB2003 font size of "about hte tailor" should be more than the "address details" as you have done in desktop view.
Also label "current stiching price" is not present in mobile view

**Comment by SubhamB2003** [comment]
> 

Hey, Now it's ok

image

**Comment by its-vikash** [comment]
> > 
> 
> @its-vikash Hey, Now it's ok
> 
> image

@SubhamB2003  Yes, can you check is it working perfectly on both desktop view and mobile view (responsiveness) and please final screenshots of both view after checking

**Comment by SubhamB2003** [comment]
> > > 
> > 
> > 
> > @its-vikash Hey, Now it's ok
> > image
> 
> @SubhamB2003 Yes, can you check is it working perfectly on both desktop view and mobile view (responsiveness) and please final screenshots of both view after checking

Uploading StichHub2.mp4…

**Comment by its-vikash** [comment]
> > > > 
> > > 
> > > 
> > > @its-vikash Hey, Now it's ok
> > > image
> > 
> > 
> > @SubhamB2003 Yes, can you check is it working perfectly on both desktop view and mobile view (responsiveness) and please final screenshots of both view after checking
> 
> Yeah I checked https://github.com/UBA-GCOEN/StichHub/assets/94003231/3ee2da65-e32d-4a4c-b9d9-d47f6c457064

@SubhamB2003 bro all things are right just correct the spelling of "appointment"

**Comment by its-vikash** [comment]
@Siddhant-Patil0203 @Naresh-chandanbatve Please check this

**Comment by SubhamB2003** [comment]
> 

I changed the spelling

**Review by Siddhant-Patil0203 — APPROVED** [review]
@SubhamB2003 @its-vikash Good to go

**Pull request merged**
