### PR TITLE
overflow issue is resolved

### PR DESCRIPTION
**Pull request by HimanshuNarware**
# Description

The overflow issue in Tailor Register is resolved, and also fix some styling issues in the registration page

Fixes # (issue)
#26

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
By using  localhost in my device and also on a small device like a mobile phone
- [x] Test A
- [x] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Before
overflow

  ## After
#Screenshot

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @HimanshuNarware!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @HimanshuNarware!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
Hey @HimanshuNarware,
Why haven't you used tailwindcss ? 
You have used plain CSS.

Use tailwindcss instead of plain css

**Comment by HimanshuNarware** [comment]
> Hey @HimanshuNarware, Why haven't you used tailwindcss ? You have used plain CSS.
> 
> Use tailwindcss instead of plain css
ok sir

**Comment by UBA-GCOEN** [comment]
Hello @HimanshuNarware!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Pull request closed without merging**
