### PR TITLE
Fixed : issue #230

### LINKED ISSUE #230: [BUG] Links not working
## Description

**Describe the bug:**
When we click on the social media icons . It redirects us to to same page . 

**Expected behavior:**
It should redirect to to their respective page . 

**Actual behavior:**
When clicked on the Social Media icons . It redirects to the same page . 

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
It should redirect to their respective Social Media platforms . 

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
stichlabissue4

## Additional Information

**Device (please complete the following information):**
- OS: [Windows
- Browser [Chrome]
- Version [e.g., 22]

**Additional context:**

### PR DESCRIPTION
**Pull request by parthpathakpp1**
# Description
I removed Instagram ,Twitter , and Whatsapp Icon for now as there are no official pages and added links to Gmail and Youtube . 

Fixes #230 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
stichlabissue4
## After
StichHubSicalmedialinksafter

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @parthpathakpp1!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by parthpathakpp1** [comment]
@Naresh-chandanbatve Can you please check the PR .

**Comment by parthpathakpp1** [comment]
@Naresh-chandanbatve @Siddhant-Patil0203 @LadeHarshal @vishal10kesharwani @Saurabb-coder Please check the PR .

**Comment by parthpathakpp1** [comment]
@UBA-GCOEN PLEASE CHECK THE PR .

**Review by Siddhant-Patil0203 — APPROVED** [review]
🙂👍

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
image
Hey @parthpathakpp1  Pls Align this icon

**Comment by parthpathakpp1** [comment]
> image Hey @parthpathakpp1 Pls Align this icon

Ok

**Comment by parthpathakpp1** [comment]
@Siddhant-Patil0203 Made the Changes Please Check . 
changesproof

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Comment by parthpathakpp1** [comment]
@Siddhant-Patil0203 Can you please give the label to this PR?

**Pull request merged**
