### PR TITLE
#138-customer navbar

### LINKED ISSUE #138: [BUG] Text not visible in our services
## Description
The text is not visible in our services
**Describe the bug:**
After logging in the text in our services is not visible .I think the text is not there. So please tell me what you want there.

scrnli_26_05_2023_16-45-47

Please assign this to me under gssoc23

### PR DESCRIPTION
**Pull request by Soulpurr**
# Description
closes #138 
@Siddhant-Patil0203  As you said to change the navbar for cloth category with the customer one so i have changed it.
Now the navbar you provided in screenshot is implemented.

Please delete options that are not relevant.

- [+] Bug fix (non-breaking change which fixes an issue)

# Screenshots
[scrnli_27_05_2023_23-10-09.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/321432b5-2b89-4a4d-8eaf-76a0d23e79cf)

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Soulpurr!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Soulpurr** [comment]
@UBA-GCOEN  can you pls approve this pr

**Comment by Soulpurr** [comment]
@Siddhant-Patil0203 i have retained the code of navbar that you said needed to be replaced. It is in navbardarkOg

**Review by UBA-GCOEN — APPROVED** [review]

**Comment by Soulpurr** [comment]
Hii @Naresh-chandanbatve  @Siddhant-Patil0203 @its-vikash  since this pr was merged pls add level and gssoc23 label  to this as due to this the leaderboard doesn't count this pr.

**Pull request merged**
