### PR TITLE
Add captcha in signin forms

### LINKED ISSUE #373: Feat: Add captcha in sign in form
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Missing Feature
There is **captcha present in the sign-up form** but there is **no captcha in sign-in form**. 
The aim of CAPTCHA is to differentiate between human users and automated bots. 
So I think we should implement it in sign-in form as well. 
I want to implement the captcha in sign-in form for both customers and the tailor.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Add a captcha in sign-in forms of user and customer

Fixes #373 Add captcha in sign in form

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Output Video

### Tailor Sign in

https://github.com/UBA-GCOEN/StichHub/assets/86224794/f4b4a5dd-2cfa-4739-b743-4690bc118bd5

### Customer Sign in

https://github.com/UBA-GCOEN/StichHub/assets/86224794/63f9e849-f757-42ab-9dac-8727da2ca840

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @AlfiyaSiddique!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve Can you please review this PR.

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Comment by Siddhant-Patil0203** [comment]
Hey @AlfiyaSiddique 
image

Check the responsiveness in tailor sign in

**Comment by AlfiyaSiddique** [comment]
Hello @Siddhant-Patil0203  

Fixed the Responsiveness.

**Review by Siddhant-Patil0203 — APPROVED** [review]
@AlfiyaSiddique Good to go

**Pull request merged**
