### PR TITLE
#174 Fixed Navbar Navigation bug with sections in landing page

### LINKED ISSUE #174: [Bug]  Navbar Navigation bug with sections in landing page
We can create separate pages for each of the sections like AboutUs, ContactUs, etc

### PR DESCRIPTION
**Pull request by ManavMalhotra**
# Description

I solved a navigation bug that affected the landing page of our website. The bug caused the sections in the Navbar to not align properly with the main page components. I fixed it by adjusting the margins and padding for each component.

Fixes #174

## Type of change
Added margin-top to improve layout
Removed padding-top to fix issue

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

## Before
https://github.com/UBA-GCOEN/StichHub/issues/174#issuecomment-1566112383

## After
https://github.com/UBA-GCOEN/StichHub/assets/64147782/987d0160-a58e-434a-bc29-3cc617c9eb32

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @ManavMalhotra!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by its-vikash — APPROVED** [review]

**Comment by ayush02av** [comment]
@ManavMalhotra Can you make the transitions a bit smoother? They're too jittery right now (as shown in the media you uploaded).

**Comment by ayush02av** [comment]
@Siddhant-Patil0203 Can you please review this issue and Pull Request. It's ready to review.

**Review by its-vikash — APPROVED** [review]

**Review by its-vikash — COMMENTED** [review]
@Siddhant-Patil0203 ready to review

**Comment by ManavMalhotra** [comment]
@Siddhant-Patil0203 please check

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
Hey @ManavMalhotra  Why did you generate stichhub/package-lock.json ??

**Review by Siddhant-Patil0203 — APPROVED** [review]
looks good

**Pull request merged**
