### PR TITLE
#367-chatbot

### LINKED ISSUE #367: Feat:Integrating chat bot in form of chat gpt.
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to integrate chat gpt chat bot in home page.

### Add Screenshots

..

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Soulpurr**
# Description
So i have added a chatbot which will answer random questions. I have used huggingface here.
[scrnli_27_06_2023_17-43-41.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/6e9b7564-9d4d-47f9-88bd-358d99cf2f68)
fixes #367

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Soulpurr!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @Soulpurr Its throwing error in deployment.
deployment link: https://stichhub-pxiptn6z4-stichhub.vercel.app/

Check what the issue

here's the Screenshot
image

**Comment by Soulpurr** [comment]
> Hey @Soulpurr Its throwing error in deployment. deployment link: https://stichhub-pxiptn6z4-stichhub.vercel.app/
> 
> Check what the issue
> 
> here's the Screenshot image

Pls give me sometime I gonna fix it soon.As currently my end sem are going on.

**Comment by Siddhant-Patil0203** [comment]
> > Hey @Soulpurr Its throwing error in deployment. deployment link: https://stichhub-pxiptn6z4-stichhub.vercel.app/
> > Check what the issue
> > here's the Screenshot image
> 
> Pls give me sometime I am gonna fix it soon.As currently my end sem are going on.

Take your time buddy @Soulpurr

**Comment by Naresh-chandanbatve** [comment]
@Soulpurr any progress

**Comment by Soulpurr** [comment]
> @Soulpurr any progress

sorry for late reply my end sem was going on.
I am creating a new pr deleting this

**Pull request closed without merging**
