### PR TITLE
feat: forgot password added

### LINKED ISSUE #154: [FEATURE REQUEST] forgot password in signin
## Description

**Problem**
There is no forgot password in sign in page

**Solution**
I will add the forgot password button and its functionality.

Please assign this issue to me under gssoc.

## to do issues
- [x] #518
- [ ] otp verification
- [ ] reset password.

### PR DESCRIPTION
**Pull request by SINJINI-G**
# Description
- forgot password component added in the frontend
- created respective route in the backend
- connected login, forgot password route, backend in both tailor and customer

Fixes #154

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @SINJINI-G!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by its-vikash** [comment]
@Naresh-chandanbatve please approve the changes and merge

**Comment by Siddhant-Patil0203** [comment]
Hey @SINJINI-G 
Forgot password workflow should be like this 👇
You should send a mail to the user's email with the password reset link, user will go to that link and reset his password, then he can log in with his new password.

Will you be able to do this ??

**Comment by Siddhant-Patil0203** [comment]
> > Hey @SINJINI-G Forgot password workflow should be like this 👇 You should send a mail to the user's email with the password reset link, user will go to that link and reset his password, then he can log in with his new password.
> > Will you be able to do this ??
> 
> Well, I had a different approach in mind that is after clicking on forgot password, a new page will open where the user needs to give his/her mail.. this mail will get verified and an otp will be sent to that mail.. having successfully sending the mail, the otp verification page will open where the user will give the otp from the mail which he/she had received.. after successful otp verification it will direct to reset password page where the user can reset the password.. this will ensure better security.. Since, this is a huge process, so I have subdivided it into a few issues: 1.forgot password feature addition, 2.otp verification and 3. reset password. Now the workflow that you have asked for is a less secure one. But I can do it if you want that.. let me know what you would prefer.

@SINJINI-G yup, otp one is better 👍, so have you made different issues for this ??

**Comment by Siddhant-Patil0203** [comment]
@SINJINI-G ?

**Comment by SINJINI-G** [comment]
> @SINJINI-G ?

Hi @Siddhant-Patil0203 !! This PR is for the first issue.. I will create the next two issues once this is merged.. or should I start working on them? What do you suggest? I will need the updated code to proceed that's why I have been waiting for this to be merged.

**Comment by Siddhant-Patil0203** [comment]
@SINJINI-G Pls resolve the conflicts from the recent push

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Comment by SINJINI-G** [comment]
> @SINJINI-G Pls resolve the conflicts from the recent push Accept the incoming changes from the push

I have resolved the conflicts. Please check

**Review by Siddhant-Patil0203 — APPROVED** [review]
👍

**Comment by Siddhant-Patil0203** [comment]
hey @SINJINI-G I have merge this, you can start working on remaining task

**Comment by Siddhant-Patil0203** [comment]
> > Hey @SINJINI-G Forgot password workflow should be like this 👇 You should send a mail to the user's email with the password reset link, user will go to that link and reset his password, then he can log in with his new password.
> > Will you be able to do this ??
> 
> Well, I had a different approach in mind that is after clicking on forgot password, a new page will open where the user needs to give his/her mail.. this mail will get verified and an otp will be sent to that mail.. having successfully sending the mail, the otp verification page will open where the user will give the otp from the mail which he/she had received.. after successful otp verification it will direct to reset password page where the user can reset the password.. this will ensure better security.. Since, this is a huge process, so I have subdivided it into a few issues: 1.forgot password feature addition, 2.otp verification and 3. reset password. Now the workflow that you have asked for is a less secure one. But I can do it if you want that.. let me know what you would prefer.

hey @SINJINI-G Have you started working on remaining issues

**Pull request merged**
