### PR TITLE
Added scroll up button to selected long pages[GSSoC'23]

### PR DESCRIPTION
**Pull request by Deepanshu0703**
Added scroll up button with arrow up key icon(react-icons) to selected long pages to scroll up it will not be visible if you are alreay at the top. Onclicking it , will take you at the top of page smoothly

### CODE REVIEW

**Comment by Naresh-chandanbatve** [comment]
Prs with no issues mentioned and assigned to you can not be merged

**Comment by Naresh-chandanbatve** [comment]
Create an issue and get assigned first

**Comment by Naresh-chandanbatve** [comment]
Then you can create new pr

**Comment by Deepanshu0703** [comment]
ya sorry for that. I have raised issue after I made this PR

**Pull request closed without merging**
