### PR TITLE
Error Page Added

### PR DESCRIPTION
**Pull request by PatilHarshh**
Error page has been added

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @PatilHarshh!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @PatilHarshh 
Which issue does it close?

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 i was about error page

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 it was about error page

Kindly link your issue with this pull request or tell me the issue no.

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 issue number #134

**Review by Siddhant-Patil0203 — COMMENTED** [review]
@PatilHarshh Why did you add client/package-lock.json this file ??

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 ops !! my bad what i have to do now?

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 ops !! my bad what i have to do now?

No issues, I have deleted it 👍

**Review by Siddhant-Patil0203 — APPROVED** [review]
@PatilHarshh Great Work ✨✅

**Comment by PatilHarshh** [comment]
thank you  @Siddhant-Patil0203  looking forward to work more in this project , please let me know if any?

**Comment by Siddhant-Patil0203** [comment]
> thank you  @Siddhant-Patil0203  looking forward to work more in this project , please let me know if any?

Yes you check out issues and contribute ☺️

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 can you use labels here so that i will count

**Pull request merged**
