### PR TITLE
Filter dropdown

### LINKED ISSUE #315: [FEATURE REQUEST] FilterSection Filter is not funtcional.
## Description

**Is your feature request related to a problem? Please describe.**
The **filter dropdown in the tailor's dashboard is not functional**. It does not filter based on the provided category. Also, the dropdown does not close automatically on clicking on one of the category which is expected as default behaviour of any dropdown.

**Describe the solution you'd like**
I want to make the dropdown filter functional. I will implement it using react states and by adding some category tag to each tailor if enough tailor info is not there. I will test it thoroughly to make sure everything works fine.

## Screenshot

If you find this feature worth implementing please assign me this issue under the gssoc'23 label.

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description

This PR contains code to make the filter dropdown functional.
Fixes #315 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# Sample Output Video

https://github.com/UBA-GCOEN/StichHub/assets/86224794/9c352047-607f-452d-a525-a6345d615b37

### CODE REVIEW

**Review by Siddhant-Patil0203 — APPROVED** [review]
Great Work 🚀✨ @AlfiyaSiddique

**Review by Siddhant-Patil0203 — COMMENTED** [review]
Hey @AlfiyaSiddique can you add a **clear all** button which will clear all the applied filter ??

**Comment by AlfiyaSiddique** [comment]
> Hey @AlfiyaSiddique can you add a **clear all** button which will clear all the applied filter ??

Sure, Will add it soon

**Comment by AlfiyaSiddique** [comment]
Hey **@Siddhant-Patil0203** 
 Implemented a clear Filter button.

## Sample Video

https://github.com/UBA-GCOEN/StichHub/assets/86224794/f232fcbd-651b-4ff9-8ec4-01b9b2a14520

**Review by Siddhant-Patil0203 — APPROVED** [review]
@AlfiyaSiddique looks cool,
Good to go 🚀✨

**Pull request merged**
