### PR TITLE
Linking of Pages Upadated

### LINKED ISSUE #330: BUG: Not Proper linking (Buttons are not working
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Buttons not working

### Add ScreenShots

Screenshot (88)

### What browser are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by PatilHarshh**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #330 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

## After

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @PatilHarshh!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 please review it

**Review by Siddhant-Patil0203 — APPROVED** [review]
@PatilHarshh Looks Good

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
@PatilHarshh Your Linking isn't working, check the preview site

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 can you check now !!

**Comment by Siddhant-Patil0203** [comment]
Hey @PatilHarshh Please resolve the conflicts

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203

**Review by Siddhant-Patil0203 — COMMENTED** [review]
@PatilHarshh good to go

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Pull request merged**
