### PR TITLE
Fixed the z-index and alignments on demo dress change button on landing page.

### PR DESCRIPTION
**Pull request by iasadk**

### CODE REVIEW

**Comment by raghav1030** [comment]
heyy which api keys did you use in the .env file? I'm struggling to find them..

**Comment by Naresh-chandanbatve** [comment]
Provide screenshots and more description on what changes have you done

**Comment by Naresh-chandanbatve** [comment]
> heyy which api keys did you use in the .env file? I'm struggling to find them..

We can not share our api keys as its confidential.

You can create your account on mongodb and get mongodb apis
Similarly google api and cashfree as well

**Comment by iasadk** [comment]
> Does it closes #54

Yes I have raised the PR for the FIX and also comments a description for this PR

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
