### PR TITLE
Major feature text update

### LINKED ISSUE #378: [STYLE CHANGE] Change the Major Feature text style
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

I want to change the Major Feature text style

### Reason for Change:

The Major feature text is making the website out and inconsistent.

### Current Styling:

It's too small and very different

### Proposed Styling:

To make it consistent with whole page design

### Screenshots or Design Mockups (optional):

Screenshot from 2023-06-23 11-19-04

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MisterMickey**
# Description

Major feature text fix

Fixes #378 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I've ran it on local server

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# Screenshots

## Before
Screenshot from 2023-06-28 15-49-41

## After
Screenshot from 2023-06-28 15-49-28

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @MisterMickey!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @MisterMickey 
The font size is very large, it's not going well with the overall UI,
Try enhancing it more and keep the font size between small-medium.
Also, you can do more additional changes in that section to make it look nice

**Comment by Naresh-chandanbatve** [comment]
#443 this pr may create conflicts

**Comment by MisterMickey** [comment]
@Naresh-chandanbatve I don't think so I've just introduced inline style

**Comment by Siddhant-Patil0203** [comment]
> Hey @MisterMickey The font size is very large, it's not going well with the overall UI, Try enhancing it more and keep the font size between small-medium. Also, you can do more additional changes in that section to make it look nice

@MisterMickey Have you made this changes

**Comment by MisterMickey** [comment]
@Siddhant-Patil0203 Actually I haven't got the notification of that message just checked it now, Will do it in 30mins.

**Comment by MisterMickey** [comment]
@Siddhant-Patil0203 Done! Decreased the font size to 2 rem and it's looking nice now.

**Comment by Naresh-chandanbatve** [comment]
LGTM
@Siddhant-Patil0203

**Review by Naresh-chandanbatve — APPROVED** [review]

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
