### PR TITLE
added improvement feature

### LINKED ISSUE #351: Backend: improvement/refining after stiching needed by customer
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

There are cases when the final order delivered has issues so to request for its restiching and improvement/refining is must. This is a must feature required by user for their positive response.
I will be creating an API for the customer to hit and request for required improvement.

### Add Screenshots

Not found an image to show, basically there will be an improvement button in the order section like refund.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by SnehaJaiswal123**
# Description

I have added a feature for the customer to request improvement after order received unfit.

Fixes #351 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## After
stichhub

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @SnehaJaiswal123!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
@SnehaJaiswal123 Haven't you added the button in the frontend part?

**Comment by SnehaJaiswal123** [comment]
> @SnehaJaiswal123 Haven't you added the button in the frontend part?

No, I have just done the backend part.

**Comment by Siddhant-Patil0203** [comment]
Alright, @SnehaJaiswal123 Will review it shortly, btw if you are interested to add the frontend part, so can also make an issue for this, pls. let me know this.

**Comment by Naresh-chandanbatve** [comment]
hey @SnehaJaiswal123 
you have added package.json and package-lock.json  in the root folder it should be either in server or in client/stichhub

add the dependencies in client/StichHUb or in server
remove package-lock.json and package.json from root folder

**Comment by SnehaJaiswal123** [comment]
> hey @SnehaJaiswal123 you have added package.json and package-lock.json in the root folder it should be either in server or in client/stichhub
> 
> add the dependencies in client/StichHUb or in server remove package-lock.json and package.json from root folder

Done, Corrected and created new pull request

**Comment by Naresh-chandanbatve** [comment]
@SnehaJaiswal123 
its always a great practice to do all the changes in same pr until it is merged and not create another for same issue.
it helps in keeping the projects pr history clean.

**Comment by SnehaJaiswal123** [comment]
> @SnehaJaiswal123 its always a great practice to do all the changes in same pr until it is merged and not create another for same issue. it helps in keeping the projects pr history clean.

Sorry, will take care of it by next. Thanks!

**Pull request closed without merging**
