### PR TITLE
Update social media hyperlink

### LINKED ISSUE #382: BUG: Social icons redirecting to github only
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Social icons redirecting to github only

### Add ScreenShots

Screenshot from 2023-06-23 11-32-31

### What browser are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MisterMickey**
# Description

Update social media hyperlink in footer

Fixes #382

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @MisterMickey!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @MisterMickey 
Pls. follow this guidelines 
https://github.com/UBA-GCOEN/StichHub/issues/382#issuecomment-1605737854

**Comment by MisterMickey** [comment]
> Hey @MisterMickey Pls. follow this guidelines [#382 (comment)](https://github.com/UBA-GCOEN/StichHub/issues/382#issuecomment-1605737854)

All changes  done.

**Review by Siddhant-Patil0203 — COMMENTED** [review]
@MisterMickey Looks good

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Pull request merged**
