### PR TITLE
Fixed : issue #227

### LINKED ISSUE #227: [FEATURE REQUEST] ClothesCategory Hovering
## Description

**Is your feature request related to a problem? Please describe.**
There is lot of places where there is no hovering effect . So when somebody hovers it does not show any effect . 

**Describe the solution you'd like**
I will add hovering effect and some cool animations .

**Describe alternatives you've considered**

## Additional Information

**Context**

https://github.com/UBA-GCOEN/StichHub/assets/85991449/145e83fc-10ae-428b-9761-845fec30b6d2

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

### PR DESCRIPTION
**Pull request by parthpathakpp1**
# Description
I have added hovering effects on the images and cards in Clothes Category section .

Fixes #227 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
https://github.com/UBA-GCOEN/StichHub/assets/85991449/145e83fc-10ae-428b-9761-845fec30b6d2
## After

https://github.com/UBA-GCOEN/StichHub/assets/85991449/ccf5e59c-0dee-490b-bd24-3db6b0f9e822

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @parthpathakpp1!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by parthpathakpp1** [comment]
@Naresh-chandanbatve Can you please check the PR .

**Comment by parthpathakpp1** [comment]
> # Description
> I have added hovering effects on the images and cards in Clothes Category section .
> 
> Fixes #227
> 
> ## Type of change
> * [x]  New feature (non-breaking change which adds functionality)
> 
> # Checklist:
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> * [ ]  New and existing unit tests pass locally with my changes
> * [x]  Any dependent changes have been merged and published in downstream modules
> 
> # Screenshots
> ## Before
>  stichhubissue2.mp4 
> ## After
>  StichHubafterissue.mp4 
> **Include video if needed**


@Naresh-chandanbatve @Siddhant-Patil0203 @LadeHarshal @Saurabb-coder Can you please check this PR .

**Comment by parthpathakpp1** [comment]
@Naresh-chandanbatve @Siddhant-Patil0203 @LadeHarshal @vishal10kesharwani @Saurabb-coder Please check the PR .

**Comment by parthpathakpp1** [comment]
@UBA-GCOEN PLEASE CHECK THE PR .

**Review by Siddhant-Patil0203 — APPROVED** [review]
Go to go ?

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Comment by parthpathakpp1** [comment]
@Siddhant-Patil0203 Can you please give the label to this PR?

**Pull request merged**
