### PR TITLE
"135 Logo And Home page UI Changed"

### PR DESCRIPTION
**Pull request by Ishita-Ghosh-25**
# Description

The Logo of the Home Page and the welcome message which was not clearly visible earlier have been modified

Fixes # (issue)

## Type of change 

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
image

## After
image

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Ishita-Ghosh-25!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Naresh-chandanbatve** [comment]
Hey @Ishita-Ghosh-25 
Which issue does it solves?

**Comment by Ishita-Ghosh-25** [comment]
@Naresh-chandanbatve The logo was different and the Welcome text was not clearly visible

**Comment by Naresh-chandanbatve** [comment]
Have you created issue for this one ?
If not please make an issue first and get assigned to it.

**Comment by Ishita-Ghosh-25** [comment]
@Naresh-chandanbatve I have already created an issue for this and it was assigned to me by @Siddhant-Patil0203

**Comment by Naresh-chandanbatve** [comment]
Issue no?

**Comment by Naresh-chandanbatve** [comment]
Please keep a habit of referencing your assigned issue no. in the PR

**Comment by Siddhant-Patil0203** [comment]
@Ishita-Ghosh-25 You can refer your issue like this #135 , which helps to maintainer to review your code accordingly

**Review by Siddhant-Patil0203 — APPROVED** [review]
@Ishita-Ghosh-25 
Looks good, you can use tailwindcss also, it is very easy and faster to code. 🙂

**Pull request merged**
