### PR TITLE
Delete account

### LINKED ISSUE #374: Feat: Delete Account Feature
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Proposed Feature
As a user requires a **delete account option** when he/she decided to no longer use an application.
But, Currently, there is no delete button option on both sides customers and tailors. I want to implement the delete account option and implement the delete operation in the backend which removes the user account and all the data related to that user. I will implement the backend delete operation for both the customer and the tailor.

## Method
We can do this as follows: 
When the user clicks on the delete button, an input will be prompted in which he has to put his/her username to confirm that the button is not clicked by mistake. If the correct user name is given then the delete operation will trigger in the backend.

In the input box that appears after clicking the delete button, we can give any other statement to enter by the user instead of a username for example "Don't Say Goodbye! Stay with Us" just to make the site a little fun. 

Please provide your suggestions on this if you agree to implement this feature!

### Add Screenshots

..

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Added the delete account operation

Fixes #374 **Delete Account Feature**

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Sample Output

https://github.com/UBA-GCOEN/StichHub/assets/86224794/9e09a8cf-e7fc-41a5-b176-5f7f86994f92

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @AlfiyaSiddique!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by AlfiyaSiddique** [comment]
Hey **@Siddhant-Patil0203**, What are these potential problems found by GitHub-code-scanning bot? Do I need to change something in my code?

**Comment by AlfiyaSiddique** [comment]
@Siddhant-Patil0203  ??

**Comment by Siddhant-Patil0203** [comment]
> Hey **@Siddhant-Patil0203**, What are these potential problems found by GitHub-code-scanning bot? Do I need to change something in my code?

Hey @AlfiyaSiddique 
I will look through and let you know, if there are any necessary changes required.

**Comment by Naresh-chandanbatve** [comment]
Hey @AlfiyaSiddique 
there are two issues in codeql Scanning
1>missing rate limit
2>Database query built from user-controlled sources


can resolve this one by adding rate limit using express-rate-limiter as below.
const rateLimit = require("express-rate-limit");

// Apply rate limiting middleware for each route
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // limit each IP to 100 requests per windowMs
});

router.post('/signin', limiter, signin);
router.post('/register', limiter, register);
router.post('/delete', limiter, deleteAccount);


to adress this issue just add this kind of validation and sanitation
  // Validate the email input
  if (!isValidEmail(email)) {
    throw new Error('Invalid email');
  }

  // Sanitize the email input (if necessary)
  const sanitizedEmail = sanitizeEmail(email);

**Comment by AlfiyaSiddique** [comment]
> Hey @AlfiyaSiddique there are two issues in codeql Scanning 1>missing rate limit 2>Database query built from user-controlled sources
> 
> can resolve this one by adding rate limit using express-rate-limiter as below. const rateLimit = require("express-rate-limit");
> 
> // Apply rate limiting middleware for each route const limiter = rateLimit({ windowMs: 15 * 60 * 1000, // 15 minutes max: 100, // limit each IP to 100 requests per windowMs });
> 
> router.post('/signin', limiter, signin); router.post('/register', limiter, register); router.post('/delete', limiter, deleteAccount);
> 
> to adress this issue just add this kind of validation and sanitation // Validate the email input if (!isValidEmail(email)) { throw new Error('Invalid email'); }
> 
> // Sanitize the email input (if necessary) const sanitizedEmail = sanitizeEmail(email);

Okay, Understood. Will make the changes soon.👍🏻

**Comment by AlfiyaSiddique** [comment]
Hello @Naresh-chandanbatve 

Resolved all the issues. 👍🏻

**Comment by Naresh-chandanbatve** [comment]
hey @AlfiyaSiddique 
all issues is are not solved this approach will consume more time to validate emails 
I will suggest to use email validator library to validate emails

here is an example snippet

const validator = require('email-validator');

const isValidEmail = async (email) => {
  const isValid = validator.validate(email);
  return isValid;
};
const email = 'example@gmail.com';
const result = await isValidEmail(email);
console.log(result); // Output: true

**Comment by AlfiyaSiddique** [comment]
> hey @AlfiyaSiddique all issues is are not solved this approach will consume more time to validate emails I will suggest to use email validator library to validate emails
> 
> here is an example snippet
> 
> const validator = require('email-validator');
> 
> const isValidEmail = async (email) => { const isValid = validator.validate(email); return isValid; }; const email = '[example@gmail.com](mailto:example@gmail.com)'; const result = await isValidEmail(email); console.log(result); // Output: true

Okay.

**Comment by AlfiyaSiddique** [comment]
Hello @Naresh-chandanbatve 

Implemented the requested changes.

**Comment by AlfiyaSiddique** [comment]
Hello @Naresh-chandanbatve 
Please review this PR!

**Comment by AlfiyaSiddique** [comment]
Hello @Naresh-chandanbatve 
Please review my PRs.

**Comment by Naresh-chandanbatve** [comment]
@AlfiyaSiddique 
you have added package.json in root folder this should be in /server folder 
you have installed express-rate-limit in root folder instread of server folder 

please delete package.json from root folder and run  npm install express-rate-limit in the /server folder 
 also delete package-lock.josn in the root folder it was also added by mistake earlier

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique you have added package.json in root folder this should be in /server folder you have installed express-rate-limit in root folder instread of server folder
> 
> please delete package.json from root folder and run npm install express-rate-limit in the /server folder also delete package-lock.josn in the root folder it was also added by mistake earlier

Oh okay, I apologize. Did that by mistake

**Comment by AlfiyaSiddique** [comment]
Did the Changes @Naresh-chandanbatve

**Comment by Siddhant-Patil0203** [comment]
Hello @AlfiyaSiddique,

I noticed that your routes do not have authorization for deleting user accounts. It might be a good idea to implement user authorization using middleware such as authCustomer/authTailor. What are your thoughts on this?

**Comment by AlfiyaSiddique** [comment]
> Hello @AlfiyaSiddique,
> 
> I noticed that your routes do not have authorization for deleting user accounts. It might be a good idea to implement user authorization using middleware such as authCustomer/authTailor. What are your thoughts on this?

Yeah. completely agree with this point. Thanks for pointing this out. Will implement it soon.

**Comment by Naresh-chandanbatve** [comment]
Great work @AlfiyaSiddique 
Its nice and needed feature and it will be very helpful in development as well to create and delete accounts.

Thanks a lot for your contribution ❤️.

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
