### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by shraddha761**
add pr template here
#71

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @shraddha761!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by singh1203 — COMMENTED** [review]
LGTM.

**Comment by Naresh-chandanbatve** [comment]
Please resolve conflicts

**Review by singh1203 — APPROVED** [review]
LGTM.

**Comment by UBA-GCOEN** [comment]
Hello @shraddha761!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Naresh-chandanbatve** [comment]
@shraddha761 
It says 0 files changed 
What issues are you facing?

**Comment by UBA-GCOEN** [comment]
Hello @Naresh-chandanbatve!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Pull request closed without merging**
