### PR TITLE
Tailor detail

### LINKED ISSUE #114: Tailor Details in Tailor Dashboard
**Describe the bug**
The details of the logged in tailor inside the tailor dashboard are placeholders rather than the real detail of the tailor

**To Reproduce**
1. SignIn/ Register as a tailor
2. On the left bar, the details of the tailor show : name as 'Mr. Akash Malhotra' and e-mail as 'inaamajay007@gmail.com' which are placeholders instead of the real name and email of the logged in tailor
3. Same is relevant when you click 'Profile' in the left bar.

**Expected behavior**
Instead of the placeholder values, the details of the logged in tailor must be displayed in the Tailor Dashboard.

**Screenshots**
image
In TailorDashboard

image
In Tailor Profile

**Desktop (please complete the following information):**
 - Windows
 - chrome

**Smartphone (please complete the following information):**
 - Samsung
 - OS: Android
 - chrome

**Additional context**
To solve this issue, the name and email of the user can be taken from the localStorage of the browser and can be displayed, but in profile page to display additional information such as the address, phone no. etc, an additional API will be required which can query the database to get the information of the logged in tailor.

### PR DESCRIPTION
**Pull request by ar-ag**
# Description

Previously in the profile of the tailor, the tailor's details were placeholder value rather than the once saved in the database under 'tailorlists'. To resolve this issue I have created an API at "http://localhost:5000/tailors/specific", to get the details of the specific tailor from the database and render it under 'Profile.jsx'

Fixes #114

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Test A :  For testing the API, I made a local database on MongoDB and used Postman to check the functioning of the API.
<br/><br/>Signing in as snehal@gmail.com

image

<br/><br/>Response of the new API '/tailors/specific'

image

- [ ] Test B: For checking the client side of the application I integrated axios to localhost:5000 and made the API call from the frontend to 'tailors/specific'

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project --- done
- [ ] I have performed a self-review of my code --- done
- [ ] I have commented my code, particularly in hard-to-understand areas --- not done
- [ ] I have made corresponding changes to the documentation --- not required
- [ ] My changes generate no new warnings --- done
- [ ] New and existing unit tests pass locally with my changes --- done
- [ ] Any dependent changes have been merged and published in downstream modules --- done

# Screenshots

## Before
image
<br/><br/>
image

## After

image
<br/><br/>
image
<br/><br/>
The data of 'snehal' in local MongoDB database
image

**Include video if needed**
not required

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @ar-ag!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @ar-ag there is an error while deployment, 
Please resolve it 

error: 
image

**Comment by ar-ag** [comment]
@Siddhant-Patil0203 fixed the error.

**Comment by ar-ag** [comment]
@Siddhant-Patil0203 I have resolved the error, can you please try to deploy it now?

**Comment by ar-ag** [comment]
@Naresh-chandanbatve can you please update the tag of 'Status: changes requested' as I have already made the mentioned changes.

**Review by Naresh-chandanbatve — APPROVED** [review]

**Comment by Naresh-chandanbatve** [comment]
- [ ] Make the profile image in leftview.jsx dynamic

**Pull request merged**
