### PR TITLE
add hover and focus effect on navbar and hamburger menu links

### PR DESCRIPTION
**Pull request by Amitavpanda**
# Description

I have made the following changes:

- Added an animate on hover and focus effect to navbar links and hamburger menu links.
- Implemented an underline effect on active navbar links and hamburger menu links.
- Added `cursor-pointer` to the hamburger menu icon.

This pull request addresses the issue #210  

## Type of change

Please delete options that are not relevant.
-   Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

-    My code follows the style guidelines of this project
-    I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
-    My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Before

https://github.com/UBA-GCOEN/StichHub/assets/56599943/94a544b1-6d96-4f15-99b4-0b923dee3c7a

## After

https://github.com/UBA-GCOEN/StichHub/assets/56599943/89a38302-a768-4b9b-83c9-3d86c0f50823

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Amitavpanda!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Amitavpanda** [comment]
@vishal10kesharwani I made the changes according to the guidelines provided, please give it a review.

**Review by Siddhant-Patil0203 — CHANGES_REQUESTED** [review]
Hey @Amitavpanda pls remove your Google client id from .env.client

**Comment by Siddhant-Patil0203** [comment]
@Amitavpanda will the underline of the sections will not update as we scroll ??

**Comment by Siddhant-Patil0203** [comment]
@Amitavpanda ??

**Comment by Siddhant-Patil0203** [comment]
@Amitavpanda what's the status?

**Comment by Amitavpanda** [comment]
@Siddhant-Patil0203 Due to some issues, I would not be able to work upon it and Sorry for late response.

**Comment by Amitavpanda** [comment]
@Naresh-chandanbatve you can assign this issue to someone else.

**Comment by Naresh-chandanbatve** [comment]
Your changes will not be lost @Amitavpanda 
Thank you for your time and contribution to project ❤️❤️.

You can contribute to this project even after the end of program.

**Pull request closed without merging**
