### PR TITLE
Added linting.yml workflow

### LINKED ISSUE #352: Feat: Add a Prettier Linter Workflow
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

To ensure proper and consistent linting of the codebase, include the prettier linter.

For a project with many contributors to ensure greater code readability for users, a proper linting style must be upheld.

Automated linting checks using the prettier linter in GitHub activities are an ideal way to accomplish this.

### Add Screenshots

I want to work on this issue.
Please assign me the task under GSSoC'23.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by abhinav-m22**
# Description

Added the prettier linter to ensure proper and uniform linting of the codebase.

* Fixes #352 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @abhinav-m22!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
@abhinav-m22 bro this was pretty fast 🚀

**Review by Siddhant-Patil0203 — APPROVED** [review]
@abhinav-m22 good to go

**Comment by Siddhant-Patil0203** [comment]
Hey @abhinav-m22 Check why linting is failing

**Comment by abhinav-m22** [comment]
Sorry I forgot to mention
For the linter to run successfully please open the settings of the repo go to Actions -> General -> workflow permissions and enable read and write permissions.

image

**Comment by Siddhant-Patil0203** [comment]
> Sorry I forgot to mention For the linter to run successfully please open the settings of the repo go to Actions -> General -> workflow permissions and enable read and write permissions.
> 
> image

@abhinav-m22 It already has read and writes permissions

**Comment by abhinav-m22** [comment]
As per the error and it's exit code, it cannot access the repository due to permissions.

image


Please go through this URL path and recheck : https://github.com/UBA-GCOEN/StichHub/settings/actions

**Pull request merged**
