### PR TITLE
Fixed Navbar & Hover Effect

### PR DESCRIPTION
**Pull request by arin-paliwal**
## Pull Request: Fixed Navbar & Hover Effect

This pull request addresses two specific issues related to the website's navbar: fixing its positioning and improving the hover effect.
Allow me to make more appealing UI Changes
Assign it to me

### Changes Made

1. **Fixed Navbar Positioning**: The navbar was previously not fixed, causing it to scroll along with the page content. This pull request adds the necessary CSS code to fix the navbar to the top of the page, ensuring it remains visible at all times, even when scrolling.

2. **Improved Hover Effect**: The existing hover effect on the navbar items was not visually appealing. This pull request introduces a new hover effect that enhances the user experience. Now, when a user hovers over a navbar item, the item changes color or background, providing a clear indication of interactivity.

### Screenshots

image
image

The screenshot above showcases the changes made in this pull request. On the left side, you can see the navbar before the fixes, while on the right side, the updated version is displayed.

### Testing

The changes made in this pull request were thoroughly tested to ensure their effectiveness and compatibility across different devices and browsers. The following tests were conducted:

- Checked the navbar's fixed positioning on various screen sizes and resolutions.
- Tested the hover effect on different navbar items to ensure consistent behavior and visual feedback.

### Additional Notes

This pull request adheres to the project's coding conventions and follows best practices for front-end development. It aims to improve the user experience and provide a more polished and professional appearance to the website.

Please review the changes made in this pull request and provide any feedback or suggestions for further improvement.

### CODE REVIEW

**Comment by Naresh-chandanbatve** [comment]
Why there is a change in readme.md

**Comment by Naresh-chandanbatve** [comment]
Please resolve conflicts

**Comment by arin-paliwal** [comment]
> Please resolve conflicts

I haved fixed the conflicts

**Comment by Naresh-chandanbatve** [comment]
Does it reference #39 ?

**Comment by arin-paliwal** [comment]
> Add scroll effect on it Like it should be transparent first and when it is scrolled then you make it opaque And dont make it completely opaque add some transperancy

Done
Added the scroll effect when it is not scrolled navbar is transparent otherwise it is inherited as background i.e. opaque

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
