### PR TITLE
Signup-login container fix

### LINKED ISSUE #471: Content Overflow
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

There is content overflow in register and login page of both the user and customer at 100% default zoom value. 

### Reason for Change:

The register button and some contents are not visible.

### Current Styling:

**Register**

**Login**

### Proposed Styling:

There are two ways we can tackle this design problem, these are as follows:

1. By increasing the parent size so that the screen can be scrolled and the content can be appear
2. By reducing the form field sizes.
Let me know which way to use to solve this problem.

### Screenshots or Design Mockups (optional):

_No response_

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Fix the signup and login container of tailor and customer so that content is not overflowed and hidden.

Fixes #471
closes #471 **Content Overflow** 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
**Full content is not displayed due to fixed height**

https://github.com/UBA-GCOEN/StichHub/assets/86224794/bec1fda7-814d-4ec5-bb34-a6589e66f599

## After

https://github.com/UBA-GCOEN/StichHub/assets/86224794/b791ba81-ccb0-41b9-85e7-faa118b09172

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @AlfiyaSiddique!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve and @Siddhant-Patil0203 
This might be my last PR for the gssoc23 event. So I request you to review it as soon as possible before the gssoc23 deadline.

It's been a great journey to be a contributor of this amazing repo. 🙌🏻
Definitely, I'm going to contribute to this repo even after the gssoc23 event. 

This repo has one of the most guiding and responsive mentors and maintainers among all the repos that I have contributed in during this event. 👍🏻
Thank you for your efforts and guidance.  🙂

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve please review this PR before 12 am !!

**Comment by Naresh-chandanbatve** [comment]
I think the issue is resolved 
Can you compare above deployment with https://StichHub.vercel.app in your device

**Comment by AlfiyaSiddique** [comment]
No @Naresh-chandanbatve , it's not resolved the content is overflowed at 100% default zoom because which the **Already a user? sign in** line is not visible.  So I remove the fixed height add changed some styles: 

The above video in Pr screenshot section is from latest deployment only

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve  Here again is the video from the latest deployment which has the overflow content hidden issue. 👇🏻👇🏻


https://github.com/UBA-GCOEN/StichHub/assets/86224794/1c31a6b9-4e61-4a5d-9563-f37578709e71

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve  ??

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve only one hour left, please review.

**Comment by Naresh-chandanbatve** [comment]
@AlfiyaSiddique 
the logo of stichhub at bottom corners is not adjusting accordingly
like when we click on sign in it gets miss aligned

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique 
> the logo of stichhub at bottom corners is not adjusting accordingly
> like when we click on sign in it gets miss aligned
> 
> 
> 
> 
> https://github.com/UBA-GCOEN/StichHub/assets/70953218/736ced78-9c3a-41e3-a4f0-bdce0bcaef8d
> 
> 

Okay will fix it tomorrow

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve  Fixed the logo issue


https://github.com/UBA-GCOEN/StichHub/assets/86224794/c83bf9fe-a720-45c1-8e3e-9791a2773e17

**Comment by AlfiyaSiddique** [comment]
> great @AlfiyaSiddique
> 
> we appreciate your contribution to our project and as you know our project thoroughly, we would like to have you as our maintainer to help other new contributors and guide them you can always ping us if you need any help.
> 
> you can join this discord server https://discord.gg/FQehM2v7hh and pick the maintainer role. this discord server will ping you if any new issues or pull requests are created.

Thank You @Naresh-chandanbatve for this role.
Glad to be a part of this project.

**Pull request merged**
