### PR TITLE
Resolved Issue #236 : Added FAQ section

### LINKED ISSUE #236: [FEATURE REQUEST] Creating an FAQ section
## Description

**Is your feature request related to a problem? Please describe.**
I would like to create a FAQ section for site, which answers the basic Qs of the user. 
It would be redirected to the contact us page

**Describe the solution you'd like**
Sample :-> 
Screenshot 2023-06-01 at 8 30 07 AM

If you have any other questions or need further assistance, Please don't hesitate to _**contact**_ our customer support team. We are here to help you!

**Describe alternatives you've considered**
Plz assign this task to me under gssoc'23.

### PR DESCRIPTION
**Pull request by abhi03ruchi**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #236 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
-
## After

https://github.com/UBA-GCOEN/StichHub/assets/105661636/ac27b390-42e8-4032-a674-645ad19bd850

Screenshot 2023-06-05 at 12 45 30 AM

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @abhi03ruchi!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
@abhi03ruchi Please resolve the conflicts

**Comment by Siddhant-Patil0203** [comment]
and @abhi03ruchi  pin me, if you have any difficulty will resolving the conflicts

**Comment by abhi03ruchi** [comment]
I am getting this error , shall I create another pr ? :- 

https://github.com/UBA-GCOEN/StichHub/assets/105661636/b6299ecc-dcbc-47cb-a7db-fbf8eed5119e

**Comment by Siddhant-Patil0203** [comment]
> I am getting this error 🥲, shall I create another pr ?:-
> 
>  Screen.Recording.2023-06-13.at.5.13.56.PM.mov

Okay, pull all the new changes locally and then create another pull request. 
Pin me if the resolve still exists in new PR @abhi03ruchi

**Comment by abhi03ruchi** [comment]
plz check now

**Comment by abhi03ruchi** [comment]
I have created another pr #305 . Plz review and merge it.

**Pull request closed without merging**
