### PR TITLE
#53-button-fix

### PR DESCRIPTION
**Pull request by Soulpurr**
Now the getting started button is fixed.
The issue was that too much padding in x was given for small screens , so i just changed padding in x to 1% so that the issue can be solved.

### CODE REVIEW

**Comment by Soulpurr** [comment]
@UBA-GCOEN  i m kind of new to this but i have created pull request for both of my assigned issues i.e button fix #53 and not able to type issue #55.

**Comment by UBA-GCOEN** [comment]
Hello @Soulpurr!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @Naresh-chandanbatve!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Soulpurr** [comment]
Hey @Naresh-chandanbatve can you please approve the pr.

**Comment by Naresh-chandanbatve** [comment]
So it will close 55 and 53?

**Review by Naresh-chandanbatve — APPROVED** [review]

**Comment by Soulpurr** [comment]
Hey @Naresh-chandanbatve can you add gssoc 23 label here in this pr

**Comment by Soulpurr** [comment]
Hii @Naresh-chandanbatve  @Siddhant-Patil0203 @its-vikash  since this pr was merged pls add level and gssoc23 label  to this as due to this the leaderboard doesn't count this pr.

**Pull request merged**
