### PR TITLE
Added hover github icons for the contributors.

### LINKED ISSUE #62: Adding socials hover effect to the contributors
image
Allow users to connect with the creators of the website.
Adding a hover effect over their image for their socials. HOver effect will emerge from down to up along with GitHub/LinkedIn socials of the contributors/creators.

Please assign this issue to me under GSSoC'23 label :)

### PR DESCRIPTION
**Pull request by Akanksha-202**
# Description

Added hover icons over the images of contributors on the landing page.
I added the font awesome dependency and included it in the package.json file too which is among the committed files.

Note: Please add the correct GitHub links of the contributors in the code.

Fixes #62 

## Type of change

Please delete options that are not relevant.

- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before
image

## After
image

**Include video if needed**
 Here's the video preview:
https://www.loom.com/share/64b0d25cbce1412b9d167107d3123fb5

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Akanksha-202!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @Akanksha-202!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by UBA-GCOEN** [comment]
Hello @Naresh-chandanbatve!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by Naresh-chandanbatve — APPROVED** [review]

**Comment by Akanksha-202** [comment]
@UBA-GCOEN kindly add a label to the Pr, please! 
Add GSSoC label too

**Pull request merged**
