### PR TITLE
Add Email Validation.

### LINKED ISSUE #148: [BUG] Apply input validation
## Description

**Describe the bug:**
I'm able to keep the password field empty while registering
**Expected behavior:**
There should be validation of password and email 
**Actual behavior:**
I should see error messaging saying password field cannot be empty.

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
# Description
Added email input validation

Fixes #148

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @kailashchoudhary11!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @kailashchoudhary11 ,
You have only added the email validation for Customer signup
Also add the validation for tailor signup, the controller path will be server/controllers/userTailor.js

**Comment by kailashchoudhary11** [comment]
Done @Siddhant-Patil0203

**Comment by UBA-GCOEN** [comment]
Hello @kailashchoudhary11!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and have read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Pull request merged**
