### PR TITLE
Add icon to describe form

### LINKED ISSUE #381: Feat: Add icon to describe issue input
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

It's a icon that describe the input field as issue description

### Add Screenshots

Screenshot from 2023-06-23 11-29-57

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MisterMickey**
# Description

Add icon to describe issue input

Fixes #381 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

# Screenshots

## Before
Screenshot from 2023-06-30 12-00-16

## After
Screenshot from 2023-06-30 11-59-17
 needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @MisterMickey!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Review by Siddhant-Patil0203 — APPROVED** [review]
@MisterMickey Looks good

**Comment by Naresh-chandanbatve** [comment]
Build is failing as you haven't exported describe 
Please export it.

Screenshot_2023_0704_010016

**Comment by MisterMickey** [comment]
> @MisterMickey Build is failing as you haven't exported describe Please export it.
> 
> Screenshot_2023_0704_010016

@Naresh-chandanbatve Resolved!!

**Pull request merged**
