### PR TITLE
Fixed all UI/UX bugs in #35

### LINKED ISSUE #35: UI/UX Frontend Improvments
UI/UX improvements -

### PR DESCRIPTION
**Pull request by Malay-dev**
# Description

I have added a div scroll for the Tailor Guide, now it does not overflow in the screen. Fixed the configurator page options. Removed horizontal scroll for better User experiance.

Fixes #35 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue) - fixed the UI/UX bugs by changing tailwind CSS to the components.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

## After
image
image
image

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Malay-dev!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Siddhant-Patil0203** [comment]
Hey @Malay-dev 
the Configurator bug was already resolved in some of the issues,by adding a scroll bar
Check https://stichhub.vercel.app/configurator 
Here is the Ss 
image

So kindly retrieve the current changes from that files
ie. **client/StichHub/src/components/Configurator/Navbar.jsx**  & 
**client/StichHub/src/pages/ThreeDConfigurator.jsx**

Also, there is some minor change in **client/StichHub/src/components/Home/Navbar.jsx** also change it with current code

**Comment by Malay-dev** [comment]
Hey, I have made the requested changes. Please review again...

**Review by Siddhant-Patil0203 — APPROVED** [review]
looks good👍

**Pull request merged**
