### PR TITLE
Added Social icons

### LINKED ISSUE #283: [FEATURE REQUEST] Add icons to social
## Description

**Is your feature request related to a problem? Please describe.**
I want to add icons to the social. Please assign me this issue. Thank you!

**Describe the solution you'd like**
Add icons of github and twitter.

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Description

I have added the social icons. Please review my pr and merge it. Thank you!

Fixes #283 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before

image

## After

image

**Include video if needed**

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @sumitkr2000!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by its-vikash** [comment]
@Naresh-chandanbatve please merge this, all things are fine...

**Comment by sumitkr2000** [comment]
Hey, @Naresh-chandanbatve Can you please tell me the flow of code? I have added the testimonials but don't know where to include them. It isn't very clear!!

**Review by Siddhant-Patil0203 — APPROVED** [review]

**Comment by sumitkr2000** [comment]
@Siddhant-Patil0203 Please add level tag

**Pull request merged**
