### PR TITLE
Custom Price-range Input

### LINKED ISSUE #430: Feat: Add custom price range in filter section
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add inputs in the filter for custom price ranges that can be given by users. I will add this feature along with functionality.

### Add Screenshots

I want to add custome price range feature in filter box similar to the one in amazon's site, as shown below:

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
# Description
Added Custom Price Range input in Filter Section

Fixes #430 
**Add custom price range in filter section** 
closes #430

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @AlfiyaSiddique!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Naresh-chandanbatve** [comment]
@AlfiyaSiddique 
Please make the input font white for custom range

Also  if we click on go without entering anything in custom range input it should not do anything. Currently it gives warning.

Because if we don't select custom and select range from given options and then if we click on go it still gives warning

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique Please make the input font white for custom range
> 
> Also if we click on go without entering anything in custom range input it should not do anything. Currently it gives warning.
> 
> Because if we don't select custom and select range from given options and then if we click on go it still gives warning

@Naresh-chandanbatve Did the changes for removing the warning, But I have not changed the input font color to white yet cause if we do so the text will not be visible on the white background input


https://github.com/UBA-GCOEN/StichHub/assets/86224794/5a0fd627-0f4a-4b1f-aa54-ae6675ee0a4c

**Comment by AlfiyaSiddique** [comment]
> @Naresh-chandanbatve Did the changes for removing the warning, But I have not changed the input font color to white yet cause if we do so the text will not be visible on the white background input
> 

@Naresh-chandanbatve , What do you say, should I still change the font color to white?

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve please review my PRs!! 
And you might have forgotten to add gssoc labels on my merged pr #441. Can you please add the labels.
Thank you ✨

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve please review the PRs

**Review by Naresh-chandanbatve — APPROVED** [review]

**Pull request merged**
