### PR TITLE
#244-cloths-category

### LINKED ISSUE #244: [BUG] cloth category section
## Description

**Describe the bug:**
Scroll in x axis is getting out of page
Or we can overflow in x axis in cloth section 

https://github.com/UBA-GCOEN/StichHub/assets/92094765/8244638c-3636-4dee-a998-089b95100db1

https://github.com/UBA-GCOEN/StichHub/assets/92094765/e64a089c-7513-4874-a2e5-f18d640822d9

This issue arises in mobile devices
Pls assign this to me under gssoc23

### PR DESCRIPTION
**Pull request by Soulpurr**
# Description
I have fixed the overflow in x axis.
fixes #244 

[scrnli_02_06_2023_19-15-54.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/e8b06960-36ee-4cbb-a92b-ab412ad6a67b)

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Soulpurr!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not refer respected pr and please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Soulpurr** [comment]
@Siddhant-Patil0203 pls check if it fixes overflow in x axis on your side

**Comment by Soulpurr** [comment]
Hey @Siddhant-Patil0203 can you pls verify this.

**Comment by Soulpurr** [comment]
@Naresh-chandanbatve can you approve this.

**Review by Siddhant-Patil0203 — APPROVED** [review]
good to go

**Comment by Soulpurr** [comment]
Hii @Naresh-chandanbatve  @Siddhant-Patil0203 @its-vikash  since this pr was merged pls remove under review label as due to this the leaderboard doesn't count this pr.

**Pull request merged**
