### PR TITLE
issue-367

### LINKED ISSUE #367: Feat:Integrating chat bot in form of chat gpt.
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to integrate chat gpt chat bot in home page.

### Add Screenshots

..

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Soulpurr**
# Description
I have succesfully added the chatbot.

Fixes #367 
[scrnli_27_07_2023_16-38-44.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/eb29394f-b962-482f-bdd3-c5cbba0260b7)

@Naresh-chandanbatve AND @Siddhant-Patil0203  do verify this one.

### CODE REVIEW

**Comment by UBA-GCOEN** [comment]
Hello @Soulpurr!
Thank you for submitting this pull request Your pull request will be reviewed by maintainers shortly. Meanwhile make sure you have referenced the respected issue in this pr Your pr will not be merged if it does not have reference to respected issue
please read our Contributing Guidelines https://github.com/UBA-GCOEN/StichHub/blob/main/CONTRIBUTING.md And Code of Conduct https://github.com/UBA-GCOEN/StichHub/blob/main/CODE_OF_CONDUCT.md

**Comment by Naresh-chandanbatve** [comment]
@Soulpurr 
mistakenly your changes has been removed 
can you repush the local changes to your main branch again
if the are still present locally?

**Comment by Soulpurr** [comment]
> @Soulpurr mistakenly your changes has been removed can you repush the local changes to your main branch again if the are still present locally?

Okk will push it

**Comment by Soulpurr** [comment]
> @Soulpurr mistakenly your changes has been removed can you repush the local changes to your main branch again if the are still present locally?

i have repush the code .But  there are some conflicts do can you mind fixing them as i have no idea how to fix them

**Pull request closed without merging**
